export const FEATURES_MAP: Record<string, string> = {
  gym: 'Academia',
  barbecue: 'Churrasqueira',
  cinema: 'Cinema',
  gourmet_space: 'Espaço gourmet',
  garden: 'Jardim',
  pool: 'Piscina',
  playground: 'Playground',
  squash_court: 'Quadra de squash',
  tennis_court: 'Quadra de tênis',
  sports_court: 'Quadra poliesportiva',
  party_hall: 'Salão de festas',
  game_room: 'Salão de jogos',
  accessibility: 'Acesso para deficientes',
  bike_rack: 'Bicicletário',
  coworking: 'Coworking',
  elevator: 'Elevador',
  laundry: 'Lavanderia',
  sauna: 'Sauna',
  spa: 'Spa',
  gated_community: 'Condomínio fechado',
  electronic_gate: 'Portão eletrônico',
  security_24h: 'Portaria 24h',
};

export const CONDO_FEATURES = [
  { id: 'gym', name: 'Academia' },
  { id: 'barbecue', name: 'Churrasqueira' },
  { id: 'cinema', name: 'Cinema' },
  { id: 'gourmet_space', name: 'Espaço gourmet' },
  { id: 'garden', name: 'Jardim' },
  { id: 'pool', name: 'Piscina' },
  { id: 'playground', name: 'Playground' },
  { id: 'squash_court', name: 'Quadra de squash' },
  { id: 'tennis_court', name: 'Quadra de tênis' },
  { id: 'sports_court', name: 'Quadra poliesportiva' },
  { id: 'party_hall', name: 'Salão de festas' },
  { id: 'game_room', name: 'Salão de jogos' },
  { id: 'accessibility', name: 'Acesso para deficientes' },
  { id: 'bike_rack', name: 'Bicicletário' },
  { id: 'coworking', name: 'Coworking' },
  { id: 'elevator', name: 'Elevador' },
  { id: 'laundry', name: 'Lavanderia' },
  { id: 'sauna', name: 'Sauna' },
  { id: 'spa', name: 'Spa' },
  { id: 'gated_community', name: 'Condomínio fechado' },
  { id: 'electronic_gate', name: 'Portão eletrônico' },
  { id: 'security_24h', name: 'Portaria 24h' },
];

export const CONDO_FEATURE_GROUPS = [
  {
    category: 'LAZER E ESPORTE',
    features: [
      { id: 'gym', name: 'Academia' },
      { id: 'barbecue', name: 'Churrasqueira' },
      { id: 'cinema', name: 'Cinema' },
      { id: 'gourmet_space', name: 'Espaço gourmet' },
      { id: 'garden', name: 'Jardim' },
      { id: 'pool', name: 'Piscina' },
      { id: 'playground', name: 'Playground' },
      { id: 'squash_court', name: 'Quadra de squash' },
      { id: 'tennis_court', name: 'Quadra de tênis' },
      { id: 'sports_court', name: 'Quadra poliesportiva' },
      { id: 'party_hall', name: 'Salão de festas' },
      { id: 'game_room', name: 'Salão de jogos' },
    ],
  },
  {
    category: 'COMODIDADES E SERVIÇOS',
    features: [
      { id: 'accessibility', name: 'Acesso para deficientes' },
      { id: 'bike_rack', name: 'Bicicletário' },
      { id: 'coworking', name: 'Coworking' },
      { id: 'elevator', name: 'Elevador' },
      { id: 'laundry', name: 'Lavanderia' },
      { id: 'sauna', name: 'Sauna' },
      { id: 'spa', name: 'Spa' },
    ],
  },
  {
    category: 'SEGURANÇA',
    features: [
      { id: 'gated_community', name: 'Condomínio fechado' },
      { id: 'electronic_gate', name: 'Portão eletrônico' },
      { id: 'security_24h', name: 'Portaria 24h' },
    ],
  },
];
