"""Add unique constraints to User model

Revision ID: 9fa3422b2f62
Revises: 95274d9d616c
Create Date: 2025-08-26 18:59:22.051955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa3422b2f62'
down_revision: Union[str, Sequence[str], None] = '95274d9d616c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add new composite unique constraints
        batch_op.create_unique_constraint('_username_tenant_uc', ['username', 'tenant_id'])
        batch_op.create_unique_constraint('_email_tenant_uc', ['email', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Drop new composite unique constraints
        batch_op.drop_constraint('_username_tenant_uc', type_='unique')
        batch_op.drop_constraint('_email_tenant_uc', type_='unique')
    # ### end Alembic commands ###
